title:         "Page title"
header_title:  "Header Title"
email:         "igor.l.semenov@gmail.com"
author:        И.Л.Семенов
description:   "My blog description"
baseurl:       ""
date_format:   "%-d.%m.%Y"
lang:          ru-RU
encoding:      utf-8
url:           https://igorlsemenov.github.io/math/
permalink:     pretty
highlighter:   rouge
