title:         Page title
header_title:  Header title
email:         igor.l.semenov@gmail.com
author:        И.Л.Семенов
description: >
  My blog description
baseurl:       "/math"
date_format:   "%-d.%m.%Y"
lang:          ru-RU
encoding:      utf-8
url:           http://igorlsemenov.github.io/
markdown:      kramdown
